version: '3.2'

services:
  nestbot:
    container_name: nestbot
    build: ./NestBot
    restart: always
    environment:
      TZ: Europe/Berlin
      LC_ALL: de_DE.UTF-8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./NestBot/config.json:/usr/src/app/config.json
    networks:
      - default
    logging:
      driver: none